/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import control.ControlFrmTabulator;
import java.awt.Toolkit;

/**
 *
 * @author pojbuitrago
 */
public class FrmTabulator extends javax.swing.JFrame {
    ControlFrmTabulator control;
    /**
     * Creates new form FrmTabulator
     */
    public FrmTabulator() {
        initComponents();
        this.setLocationRelativeTo(null);
        control = new ControlFrmTabulator(this);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(this.getClass().getResource("/img/logo32x32.png")));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInitValue = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        spTabSize = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtEndValue = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        btnTab = new javax.swing.JButton();
        btnRemSpaces = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mniExit = new javax.swing.JMenuItem();
        mnuEdit = new javax.swing.JMenu();
        mniCopyEndValueToClipBoard = new javax.swing.JMenuItem();
        mnuHelp = new javax.swing.JMenu();
        mniAbout = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JTabulator - Ferchoman09");
        setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        setName("frmTabulator");

        txtInitValue.setColumns(90);
        txtInitValue.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        txtInitValue.setRows(5);
        txtInitValue.setText("Acá Valor Inicial");
        txtInitValue.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtInitValue);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setText("Espacios Izquierda");

        spTabSize.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        spTabSize.setModel(new javax.swing.SpinnerNumberModel(4, 0, 10, 1));

        txtEndValue.setColumns(90);
        txtEndValue.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        txtEndValue.setRows(5);
        txtEndValue.setText("Acá Valor Final");
        txtEndValue.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtEndValue);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Columnas");

        jSpinner2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(90, 50, 1000, 1));
        jSpinner2.setEnabled(false);

        btnTab.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnTab.setText("Tabular");
        btnTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTabActionPerformed(evt);
            }
        });

        btnRemSpaces.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnRemSpaces.setText("Quitar Espacios");
        btnRemSpaces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemSpacesActionPerformed(evt);
            }
        });

        mnuFile.setText("Archivo");

        mniExit.setText("Salir");
        mniExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniExitActionPerformed(evt);
            }
        });
        mnuFile.add(mniExit);

        jMenuBar1.add(mnuFile);

        mnuEdit.setText("Edición");

        mniCopyEndValueToClipBoard.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        mniCopyEndValueToClipBoard.setText("Copiar Valor Final al portapapeles");
        mniCopyEndValueToClipBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCopyEndValueToClipBoardActionPerformed(evt);
            }
        });
        mnuEdit.add(mniCopyEndValueToClipBoard);

        jMenuBar1.add(mnuEdit);

        mnuHelp.setText("Ayuda");

        mniAbout.setText("Acerca de");
        mniAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAboutActionPerformed(evt);
            }
        });
        mnuHelp.add(mniAbout);

        jMenuBar1.add(mnuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spTabSize)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSpinner2)
                    .addComponent(btnTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRemSpaces, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spTabSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(btnTab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemSpaces)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTabActionPerformed
        control.tabule();
    }//GEN-LAST:event_btnTabActionPerformed

    private void btnRemSpacesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemSpacesActionPerformed
        control.removeSpaces();
    }//GEN-LAST:event_btnRemSpacesActionPerformed

    private void mniExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mniExitActionPerformed

    private void mniAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAboutActionPerformed
        DgAbout about = new DgAbout(this, true);
        about.setVisible(true);
    }//GEN-LAST:event_mniAboutActionPerformed

    private void mniCopyEndValueToClipBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCopyEndValueToClipBoardActionPerformed
        control.copyEndValueToClipBoard();
    }//GEN-LAST:event_mniCopyEndValueToClipBoardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTabulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTabulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTabulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTabulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrmTabulator().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRemSpaces;
    private javax.swing.JButton btnTab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JSpinner jSpinner2;
    private javax.swing.JMenuItem mniAbout;
    private javax.swing.JMenuItem mniCopyEndValueToClipBoard;
    private javax.swing.JMenuItem mniExit;
    private javax.swing.JMenu mnuEdit;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuHelp;
    public javax.swing.JSpinner spTabSize;
    public javax.swing.JTextArea txtEndValue;
    public javax.swing.JTextArea txtInitValue;
    // End of variables declaration//GEN-END:variables
}
